version: '3.10'
services:
  db:
    image: postgres:15
    env_file:
      - ./.env
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
#    networks:
#      - tg-book-network
  bot:
    build: .
    command: "python -m bot"
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - .:/aiogram-book-bot
#    networks:
#      - tg-book-network

volumes:
  postgres_data:

#networks:
#  tg-book-network:
#    external: true